theme: jekyll-theme-cayman
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>你的后半生</title>
</head>

<body>
<p>老师说写一首诗</p >
<p>我没什么文采</p >
<p>不才</p >
<p>写不出来</p >
<p>只能写这些</p >
<p>我也不知道怎么考上的戏文</p >
<p>实在是不懂</p >
<p>< img src="timg.jpg" width="600" height="757" /></p >
</body>
</html>
